export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POST_DETAILS = 'FETCH_POST_DETAILS';
export const SEARCH_VALUE = 'SEARCH_VALUE';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION'